[package]
name = "subkey"
version = "0.1.0"
authors = ["eropvolf <eropvolf@gmail.com>"]
edition = "2018"

[[bin]]
path = "src/main.rs"
name = "subkey"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
node-runtime = { path = "../../node/runtime" }
node-primitives = { path = "../../node/primitives" }
sc-cli = { version = "0.8.0" }
substrate-frame-cli = { version = "2.0.0" }
structopt = "0.3.14"
frame-system = { version = "2.0.0" }
sp-core = { version = "2.0.0" }

[features]
bench = []
